
services:
  db:
    image: postgres:latest
    container_name: db_club
    volumes:
      - ../data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - .env


  pgadmin:
    image: elestio/pgadmin
    container_name: pgadmin_club
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    env_file:
      - .env


  web:
    build:
      context: ..
      dockerfile: docker/dockerfiles/DockerfileWeb
      args:
        - --no-cache
    container_name: web_club
    volumes:
      - ../magirani_admin:/app
      - ../logs/django:/app/logs
      - ../logs/django_bot:/app/club_bot/bot_log
      - ../storage:/app/storage
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env


  bot:
    build:
      context: ..
      dockerfile: docker/dockerfiles/DockerfileBot
      args:
        - --no-cache
    container_name: bot_club
    volumes:
      - ../bot:/app
      - ../logs/bot:/app/logs
      - ../storage:/app/storage
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env


  nginx:
    image: nginx:latest
    container_name: nginx_club
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/conf.d/base.conf:/etc/nginx/conf.d/base.conf
      - ../magirani_admin/static:/var/html/static/
      - ../magirani_admin/staticfiles:/var/html/staticfiles/
      - ../magirani_admin/media:/var/html/media/
      - ../logs/nginx:/var/log/nginx
    restart: unless-stopped
    depends_on:
      - web


  redis:
    image: redis:latest
    container_name: redis_club
    volumes:
      - redis_data:/data


volumes:
  pgadmin_data:
  redis_data:
    driver: local


